### ISSUE TITLE
NdkCompile is no longer supported

### ISSUE THREAD

**Issue by cen2cen** [ton-blockchain/wallet-android#1]
Gradle Sync Issues in Android Studio
app/build.gradle

**INFO: The following project options are deprecated and have been removed: 
android.useDeprecatedNdk
NdkCompile is no longer supported
Affected Modules: app**

**Comment by DrKLO** [comment]
Removed in https://github.com/ton-blockchain/wallet-android/commit/eeefd204fc807703fc150f016a49f900e80d7e53.
