### ISSUE TITLE
Invoice URLs aren't recognized by the app

### ISSUE THREAD

**Issue by jvlianodorneles** [ton-blockchain/wallet-android#2]
Not sure if the issue is with Telegram client or wallet, but when we click on an invoice URL the wallet is not opened.

**Comment by DrKLO** [comment]
What app you selected to open URL? 
You will not be able to open URL within Telegram app at this moment, even if system gives you an option to open URL in it.

**Comment by jvlianodorneles** [comment]
> What app you selected to open URL?
> You will not be able to open URL within Telegram app at this moment, even if system gives you an option to open URL in it.

That's right, I tested with the Telegram official client (and beta).

**Comment by cen2cen** [comment]
![photo_2019-11-02_21-30-54](https://user-images.githubusercontent.com/54164450/68074082-d4aef380-fdc9-11e9-91c3-ae17b5e4af4c.jpg)
 I have try an apk file. it's work!

**Comment by jvlianodorneles** [comment]
New beta added the support? Anyway, now it's working. Thanks!

**Comment by DrKLO** [comment]
In 5.12.1 I added ability to select app if there installed more then one app which can handle ton:// URLs.
