### ISSUE TITLE
24 Secret Words can be screenshot after failing the test

### ISSUE THREAD

**Issue by Yamimono** [ton-blockchain/wallet-android#3]
When you see your 24 Secret Words for the first time, you cannot screenshot them for security reasons. But after this screen you'll be asked to check if you've noted down the words correctly, in the correct order. Fail the test and you'll see you'll be able to make a screenshot of the Secret Words screen.

**Comment by vitaliy10011986** [comment]
Oksana katya nastya vitaliy alla valera mario vadim natasha olya kolya lenya valya oleg sveta dima lena kostya petya tolya anjela vova gena vitya 
![Screenshot_20191102-145934_Chrome](https://user-images.githubusercontent.com/35435837/68071286-b8876400-fd81-11e9-8adc-84f2826428da.jpg)

**Comment by cen2cen** [comment]
> When you see your 24 Secret Words for the first time, you cannot screenshot them for security reasons. But after this screen you'll be asked to check if you've noted down the words correctly, in the correct order. Fail the test and you'll see you'll be able to make a screenshot of the Secret Words screen.

yeah... but not all phrase...

**Comment by cen2cen** [comment]
![photo_2019-11-02_21-30-54](https://user-images.githubusercontent.com/54164450/68074098-1d66ac80-fdca-11e9-853d-308e2f4fa626.jpg)
Android....
